"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useState, useEffect } from "react";

export default function PlannerPage() {
  const [examDate, setExamDate] = useState("2024-06-15");
  const [dailyHours, setDailyHours] = useState(6);
  const [subjects, setSubjects] = useState(["Mathematics", "Physics", "Computer Science"]);
  const [prioritySubject, setPrioritySubject] = useState("Physics (High Diff)");
  const [confidence, setConfidence] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);
  const [phase, setPhase] = useState(2);

  useEffect(() => {
    // 1. Fetch live database subjects on mount
    fetch("/api/subjects")
      .then((res) => res.json())
      .then((data) => {
        if (data.success && data.subjects && data.subjects.length > 0) {
          setSubjects(data.subjects.map((s: any) => s.title));
        }
      })
      .catch((err) => console.error("Error loading planner subjects:", err));

    // 2. Count up animation for confidence
    const interval = setInterval(() => {
      setConfidence((prev) => {
        if (prev >= 68) {
          clearInterval(interval);
          return 68;
        }
        return prev + 1;
      });
    }, 15);
    return () => clearInterval(interval);
  }, []);

  const handleHourChange = (action: "inc" | "dec") => {
    setDailyHours((prev) => {
      if (action === "inc") return Math.min(prev + 1, 16);
      return Math.max(prev - 1, 1);
    });
  };

  const handleAddSubject = () => {
    const sub = prompt("Enter new subject name:");
    if (sub && !subjects.includes(sub)) {
      setSubjects((prev) => [...prev, sub]);
    }
  };

  const handleGenerateRoadmap = async () => {
    setIsGenerating(true);
    try {
      // 1. Fetch current subjects in database to avoid duplicates
      const resSubs = await fetch("/api/subjects");
      const dataSubs = await resSubs.json();
      const existingTitles = dataSubs.success && dataSubs.subjects 
        ? dataSubs.subjects.map((s: any) => s.title.toLowerCase())
        : [];

      // 2. Add missing subjects to the database
      const colors = [
        { colorClass: "text-orange-400 bg-orange-500/10", borderColorClass: "stroke-orange-400", icon: "code" },
        { colorClass: "text-primary bg-primary/10", borderColorClass: "stroke-primary", icon: "account_tree" },
        { colorClass: "text-secondary bg-secondary/10", borderColorClass: "stroke-secondary", icon: "calculate" },
        { colorClass: "text-tertiary bg-tertiary/10", borderColorClass: "stroke-tertiary", icon: "psychology" }
      ];

      for (const sub of subjects) {
        if (!existingTitles.includes(sub.toLowerCase())) {
          const style = colors[Math.floor(Math.random() * colors.length)];
          await fetch("/api/subjects", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              title: sub,
              progress: 10,
              info: "AI Roadmap Created",
              tags: ["AI Planned", "Revision"],
              ...style
            })
          });
        }
      }

      // 3. Create roadmap tasks in database
      const priorityTitle = prioritySubject.split(" ")[0];
      const tasksToCreate = [
        {
          title: `AI Roadmap: ${priorityTitle} Intensive Drill`,
          description: `Spaced-repetition review of priority topics in ${priorityTitle}. Generated by StudyFlow AI.`,
          subject: priorityTitle,
          priority: "high",
          estimatedTime: `${dailyHours}h est.`,
          dueDate: examDate
        },
        {
          title: `AI Roadmap: ${subjects[0] || "General"} Foundation Check`,
          description: `Reviewing concepts and basic problem sets. Generated by StudyFlow AI.`,
          subject: subjects[0] || "General",
          priority: "medium",
          estimatedTime: "2h est.",
          dueDate: examDate
        }
      ];

      for (const task of tasksToCreate) {
        await fetch("/api/tasks", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            title: task.title,
            description: task.description,
            subject: task.subject,
            priority: task.priority,
            estimatedTime: task.estimatedTime,
            dueDate: task.dueDate,
            subjectColor: "bg-tertiary/20 text-tertiary border border-tertiary/30"
          })
        });
      }

      setConfidence(82); // bump confidence level
      setPhase(3); // advance to next phase
      alert("AI Study Roadmap generated! New subjects and tasks have been added to your Focus Board.");
    } catch (err) {
      console.error("Error generating AI roadmap:", err);
      alert("Could not sync AI roadmap to database.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="p-4 md:p-8 space-y-8 max-w-[1440px] mx-auto">
      {/* Title */}
      <div>
        <h2 className="font-bold text-3xl md:text-4xl text-primary mb-2">AI Study Planner</h2>
        <p className="text-on-surface-variant text-sm md:text-base font-medium">
          Tailored learning paths powered by StudyFlow AI.
        </p>
      </div>

      {/* Grid wrapper */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: Settings Panel (4 cols) */}
        <section className="lg:col-span-4 flex flex-col gap-6">
          <div className="glass-card p-6 rounded-2xl flex flex-col gap-5">
            <div className="flex items-center gap-2.5 text-primary">
              <span className="material-symbols-outlined select-none">auto_awesome</span>
              <h3 className="font-bold text-base">Planner Settings</h3>
            </div>

            <div className="space-y-4">
              {/* Exam Date */}
              <div>
                <label className="text-[10px] font-bold text-on-surface-variant mb-2 block uppercase tracking-wider">
                  EXAM DATE
                </label>
                <input
                  type="date"
                  value={examDate}
                  onChange={(e) => setExamDate(e.target.value)}
                  className="w-full bg-surface-container-lowest border border-white/10 rounded-lg p-3 text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary/30 transition-all duration-300"
                />
              </div>

              {/* Daily Hours +/- counter */}
              <div>
                <label className="text-[10px] font-bold text-on-surface-variant mb-2 block uppercase tracking-wider">
                  AVAILABLE DAILY HOURS
                </label>
                <div className="flex items-center justify-between bg-surface-container-lowest border border-white/10 rounded-lg p-3">
                  <button
                    onClick={() => handleHourChange("dec")}
                    className="material-symbols-outlined text-primary hover:text-secondary cursor-pointer select-none active:scale-90 transition-transform"
                  >
                    remove_circle_outline
                  </button>
                  <span className="font-bold text-sm text-on-surface">{dailyHours} Hours</span>
                  <button
                    onClick={() => handleHourChange("inc")}
                    className="material-symbols-outlined text-primary hover:text-secondary cursor-pointer select-none active:scale-90 transition-transform"
                  >
                    add_circle_outline
                  </button>
                </div>
              </div>

              {/* Subjects Chip List */}
              <div>
                <label className="text-[10px] font-bold text-on-surface-variant mb-2 block uppercase tracking-wider">
                  SUBJECTS
                </label>
                <div className="flex flex-wrap gap-2">
                  {subjects.map((sub, idx) => {
                    const colors = [
                      "bg-primary/20 text-primary border-primary/30",
                      "bg-secondary/20 text-secondary border-secondary/30",
                      "bg-tertiary/20 text-tertiary border-tertiary/30",
                    ];
                    return (
                      <span
                        key={sub}
                        className={`px-3 py-1 rounded-full text-xs font-bold border ${
                          colors[idx % colors.length]
                        }`}
                      >
                        {sub}
                      </span>
                    );
                  })}
                  <button
                    onClick={handleAddSubject}
                    className="bg-white/5 hover:bg-white/10 text-on-surface-variant hover:text-primary px-3 py-1 rounded-full text-xs border border-white/10 flex items-center gap-1 cursor-pointer transition-all active:scale-95"
                  >
                    <span className="material-symbols-outlined text-sm select-none">add</span> Add
                  </button>
                </div>
              </div>

              {/* Priority Select */}
              <div>
                <label className="text-[10px] font-bold text-on-surface-variant mb-2 block uppercase tracking-wider">
                  PRIORITY SUBJECT
                </label>
                <select
                  value={prioritySubject}
                  onChange={(e) => setPrioritySubject(e.target.value)}
                  className="w-full bg-surface-container-lowest border border-white/10 rounded-lg p-3 text-on-surface focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary/30 transition-all duration-300"
                >
                  <option value="Physics (High Diff)">Physics (High Diff)</option>
                  <option value="Mathematics">Mathematics</option>
                  <option value="Computer Science">Computer Science</option>
                </select>
              </div>
            </div>

            {/* CTA Generate button */}
            <button
              onClick={handleGenerateRoadmap}
              disabled={isGenerating}
              className="mt-2 bg-gradient-to-r from-primary to-secondary py-3.5 rounded-xl font-bold text-xs text-on-primary hover:shadow-[0_0_20px_rgba(209,188,255,0.45)] hover:brightness-105 active:scale-[0.98] transition-all flex items-center justify-center gap-2 group cursor-pointer disabled:opacity-50"
            >
              {isGenerating ? (
                <>
                  <span className="w-4 h-4 border-2 border-on-primary border-t-transparent rounded-full animate-spin" />
                  Generating Roadmap...
                </>
              ) : (
                <>
                  Generate AI Roadmap
                  <span className="material-symbols-outlined group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform text-base select-none">
                    bolt
                  </span>
                </>
              )}
            </button>
          </div>

          {/* Confidence Score card */}
          <div className="glass-card p-6 rounded-2xl relative overflow-hidden">
            <div className="z-10 relative">
              <h4 className="font-bold text-sm text-on-surface mb-2">Confidence Level</h4>
              <div className="flex items-end gap-2 mb-4">
                <span className="text-4xl font-bold text-secondary">{confidence}%</span>
                <span className="text-on-surface-variant text-[11px] font-medium mb-1">+12% this week</span>
              </div>
              <div className="h-2 w-full bg-surface-container-high rounded-full overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-secondary to-tertiary rounded-full transition-all duration-1000"
                  style={{ width: `${confidence}%` }}
                />
              </div>
            </div>
          </div>
        </section>

        {/* Right Column: Output Roadmaps (8 cols) */}
        <section className="lg:col-span-8 grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Adaptive Learning Roadmap Node Timeline */}
          <div className="md:col-span-2 glass-card p-6 rounded-2xl">
            <div className="flex justify-between items-center mb-6">
              <div className="flex items-center gap-3">
                <span className="material-symbols-outlined text-tertiary fill-icon select-none">map</span>
                <h3 className="font-bold text-base text-on-surface">Adaptive Learning Roadmap</h3>
              </div>
              <span className="bg-surface-container-high text-[10px] font-bold px-2.5 py-1 rounded-md border border-white/5 uppercase tracking-wider text-on-surface-variant">
                Phase {phase} of 4
              </span>
            </div>
            
            <div className="relative space-y-6 pl-4 before:absolute before:left-[21px] before:top-2 before:bottom-2 before:w-[2px] before:bg-white/10">
              {/* Node 1: Completed */}
              <div className="flex gap-6 relative">
                <div className="w-6 h-6 rounded-full bg-primary flex items-center justify-center z-10 shrink-0 text-background shadow-[0_0_8px_rgba(209,188,255,0.4)]">
                  <span className="material-symbols-outlined text-[15px] font-bold select-none">check</span>
                </div>
                <div>
                  <h5 className="text-primary font-bold text-sm leading-none">Foundational Concepts</h5>
                  <p className="text-on-surface-variant text-xs mt-1.5 leading-relaxed">
                    Completed Algebra review and Newton&apos;s Laws.
                  </p>
                </div>
              </div>

              {/* Node 2: In-Progress */}
              <div className="flex gap-6 relative">
                <div className={`w-6 h-6 rounded-full bg-background border-4 flex items-center justify-center z-10 shrink-0 ${
                  phase === 2 ? "border-secondary shadow-[0_0_12px_rgba(252,170,255,0.5)] animate-pulse" : "bg-primary text-background"
                }`}>
                  {phase > 2 && <span className="material-symbols-outlined text-[15px] font-bold select-none">check</span>}
                </div>
                <div className={phase > 2 ? "opacity-75" : ""}>
                  <h5 className={`${phase === 2 ? "text-secondary" : "text-primary"} font-bold text-sm leading-none`}>
                    Intensive Problem Solving
                  </h5>
                  <p className="text-on-surface-variant text-xs mt-1.5 leading-relaxed">
                    Focusing on Electromagnetism &amp; Calculus Integration.
                  </p>
                  {phase === 2 && (
                    <div className="mt-2.5 flex">
                      <span className="bg-secondary/10 text-secondary text-[9px] px-2 py-0.5 rounded border border-secondary/20 uppercase font-bold tracking-wider">
                        Active now
                      </span>
                    </div>
                  )}
                </div>
              </div>

              {/* Node 3: Advanced */}
              <div className="flex gap-6 relative">
                <div className={`w-6 h-6 rounded-full bg-background border-4 flex items-center justify-center z-10 shrink-0 ${
                  phase === 3 ? "border-secondary shadow-[0_0_12px_rgba(252,170,255,0.5)] animate-pulse" : "border-white/10"
                }`} />
                <div className={phase < 3 ? "opacity-40" : ""}>
                  <h5 className={`${phase === 3 ? "text-secondary" : "text-on-surface-variant"} font-bold text-sm leading-none`}>
                    Advanced Theory &amp; Simulations
                  </h5>
                  <p className="text-on-surface-variant text-xs mt-1.5 leading-relaxed">
                    Quantum mechanics intro and algorithmic complexity.
                  </p>
                  {phase === 3 && (
                    <div className="mt-2.5 flex">
                      <span className="bg-secondary/10 text-secondary text-[9px] px-2 py-0.5 rounded border border-secondary/20 uppercase font-bold tracking-wider">
                        Active now
                      </span>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Weekly focus */}
          <div className="glass-card p-6 rounded-2xl">
            <div className="flex items-center gap-3 mb-5">
              <span className="material-symbols-outlined text-primary select-none">calendar_view_week</span>
              <h3 className="font-bold text-base text-on-surface">Weekly Focus</h3>
            </div>
            <div className="space-y-4">
              <div className="p-3.5 bg-surface-container-low rounded-xl border-l-4 border-primary">
                <p className="text-[9px] font-bold text-primary mb-1 uppercase tracking-widest">MON - WED</p>
                <p className="text-sm font-bold text-on-surface">Calculus &amp; Mechanics</p>
                <p className="text-xs text-on-surface-variant mt-0.5 font-medium">Deep Focus: 4h / day</p>
              </div>
              <div className="p-3.5 bg-surface-container-low rounded-xl border-l-4 border-secondary">
                <p className="text-[9px] font-bold text-secondary mb-1 uppercase tracking-widest">THU - FRI</p>
                <p className="text-sm font-bold text-on-surface">Data Structures</p>
                <p className="text-xs text-on-surface-variant mt-0.5 font-medium">Practice Labs: 3h / day</p>
              </div>
              <div className="p-3.5 bg-surface-container-low rounded-xl border-l-4 border-tertiary">
                <p className="text-[9px] font-bold text-tertiary mb-1 uppercase tracking-widest">SATURDAY</p>
                <p className="text-sm font-bold text-on-surface">Full Mock Test</p>
                <p className="text-xs text-on-surface-variant mt-0.5 font-medium">Review Session: 6h total</p>
              </div>
            </div>
          </div>

          {/* Revision timeline */}
          <div className="glass-card p-6 rounded-2xl flex flex-col justify-between">
            <div>
              <div className="flex items-center gap-3 mb-5">
                <span className="material-symbols-outlined text-error select-none">history_edu</span>
                <h3 className="font-bold text-base text-on-surface">Mock Timeline</h3>
              </div>
              <div className="space-y-4">
                <div className="flex items-center justify-between border-b border-white/5 pb-3">
                  <div className="flex flex-col">
                    <span className="text-sm font-bold text-on-surface">Diagnostic Test</span>
                    <span className="text-xs text-on-surface-variant font-medium italic mt-0.5">Spaced Repetition Active</span>
                  </div>
                  <span className="material-symbols-outlined text-secondary fill-icon select-none">done_all</span>
                </div>
                <div className="flex items-center justify-between border-b border-white/5 pb-3">
                  <div className="flex flex-col">
                    <span className="text-sm font-bold text-on-surface">Mid-Term Mock</span>
                    <span className="text-xs text-on-surface-variant font-medium mt-0.5">Scheduled: May 12</span>
                  </div>
                  <span className="material-symbols-outlined text-outline select-none">pending</span>
                </div>
                <div className="flex items-center justify-between pb-1">
                  <div className="flex flex-col">
                    <span className="text-sm font-bold text-on-surface">Final Simulation</span>
                    <span className="text-xs text-on-surface-variant font-medium mt-0.5">Scheduled: June 05</span>
                  </div>
                  <span className="material-symbols-outlined text-outline select-none">schedule</span>
                </div>
              </div>
            </div>

            <div className="mt-6 p-4 rounded-xl bg-tertiary/5 border border-tertiary/10">
              <p className="text-xs text-tertiary italic leading-relaxed font-medium">
                &quot;AI Hint: You perform best in morning sessions. We&apos;ve shifted Mock Tests to 09:00 AM.&quot;
              </p>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
